version: '3.8'

services:
  app:
    build:
      context: /Users/nicolas/Downloads/Metafar
      dockerfile: Dockerfile
    container_name: metafar_app
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=localhost;Database=MetafarDB;User Id=sa;Password=YourStrong!Passw0rd;Trusted_Connection=False;MultipleActiveResultSets=true;TrustServerCertificate=true;
    ports:
      - "8080:8080"  # Ajusta según el puerto expuesto en tu Dockerfile
      - "5001:5001"
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: metafar_db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql    
    restart: unless-stopped

volumes:
  sqlserver_data:
    driver: local
