version: '3.8'

services:
  api:
    build:
      context: ./  # Ubicación del Dockerfile
      dockerfile: Dockerfile
    container_name: api_service
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyDatabase;User Id=sa;Password=YourStrong!Passw0rd;
    ports:
      - "8080:8080"
      - "5001:5001"
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - sql_data:/var/opt/mssql
      

volumes:
  sql_data:
    driver: local
